name: Playwright Tests in Docker

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
      TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
      JIRA_PROJECT_KEY: ${{ secrets.JIRA_PROJECT_KEY }}
      JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Create reports folder
        run: mkdir -p docker-reports

      - name: Build Docker image
        run: docker build --build-arg TEST_CMD='npm run test' -t pw-tests .

      - name: Run Playwright tests in Docker
        run: |
          docker run --rm \
            -e CI=true \
            -e TEST_USERNAME=$TEST_USERNAME \
            -e TEST_PASSWORD=$TEST_PASSWORD \
            -e JIRA_PROJECT_KEY=$JIRA_PROJECT_KEY \
            -e JIRA_TOKEN=$JIRA_TOKEN \
            -v ${{ github.workspace }}/reports:/app/reports/playwright-report \
            pw-tests:latest

      - name: Zip Playwright HTML report
        if: always()
        run: |
          cd reports
          zip -r ../playwright-report.zip .

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report.zip
