name: Playwright Tests in Docker

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
      TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Create reports folder
        run: mkdir -p docker-reports

      - name: Build Docker image
        run: docker build -t pw-tests .

      - name: Run Playwright tests in Docker
        run: |
          docker run --rm \
            -e CI=true \
            -e TEST_USERNAME=$TEST_USERNAME \
            -e TEST_PASSWORD=$TEST_PASSWORD \
            -v ${{ github.workspace }}/docker-reports:/app/playwright-report \
            pw-tests

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: docker-reports
